### ISSUE TITLE
npm installation warnings

### ISSUE THREAD

**Issue by alaninmcr** [elixir-europe/json-schema-validator#9]
When I try "npm install elixir-jsonschema-validator" I get

npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN saveError ENOENT: no such file or directory, open '/home/alson/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for elixir-jsonschema-validator@1.6.1: wanted: {"node":"10.16.3"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: elixir-jsonschema-validator@1.6.1
npm WARN enoent ENOENT: no such file or directory, open '/home/alson/package.json'
npm WARN alson No description
npm WARN alson No repository field.
npm WARN alson No README data
npm WARN alson No license field.

Is this expected

**Comment by ke4** [comment]
Hi Alan,

Sorry for the late reply.
I am going to have a look and try to address this issue as soon as possible.

Thanks for reporting it and have a nice day,

Karoly

**Comment by ke4** [comment]
Hi @alaninmcr,

We modified this repository and removed the server feauture.
Please check my reply on your other issue: [https://github.com/elixir-europe/json-schema-validator/issues/10](https://github.com/elixir-europe/json-schema-validator/issues/10)

I am going to close this issue.

Many thanks,

Karoly
